function corr_mix = corr_scale_mix_fast(dist, weights, scales)
% handles = {@unitCorrExp,@unitCorrMatern32,@unitCorrMatern52,@unitCorrGaussian,@unitCorrBessel};
w = weights;
sc = 1./scales;
p = [-sc(1)...
    sc(2) -sc(2)...
    sc(3) ((sc(3)^2)/3) -sc(3)...
    -sc(4)^2];

Ppq = [1.10*sc(5) 1.00...
       1.10*sc(5) 1.35...
       1.95*sc(5) 1.00];


corr_mix = w(1)* exp( p(1) * dist) + ...
           w(2)* (1 + p(2)*dist) .* exp( p(3)* dist) +...
           w(3)* (1 + p(4)*dist + p(5)*(dist.^2)) .* exp( p(6)*dist ) + ...
           w(4)* exp( p(7)*dist.^2 ) +...
           w(5)* (  ( Ppq(2) + Ppq(1)*dist ).*cos(sc(5)*dist) +...
                    ( Ppq(4) + Ppq(3)*dist ).*sin(sc(5)*dist) ...
                 ) ./ (  (Ppq(6)+Ppq(5)*dist) .* sqrt(1+sc(5)*dist)  );
        
       
end

